#SPDX-License-Identifier: MIT-0
---
- name: Disable root SSH login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: "PermitRootLogin {{ aws_ssh_permit_root_login }}"
    state: present
    validate: sshd -t -f %s
  notify: Restart ssh

- name: Disable password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: "PasswordAuthentication {{ aws_ssh_password_authentication }}"
    state: present
    validate: sshd -t -f %s
  notify: Restart ssh

- name: Enable public key authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: "PubkeyAuthentication {{ aws_ssh_pubkey_authentication }}"
    state: present
    validate: sshd -t -f %s
  notify: Restart ssh
